In [43]:
import numpy as np
rng = np.random.default_rng(seed= 1701) # seed for reproducibility
x1= rng.integers(10, size= 6) 
print("x1 : ",x1)
x2= rng.integers(10, size=(3,4)) # two-dimensional array
print("x2 : ",x2)
x3= rng.integers(10, size= (3, 4, 5)) #three-dimensional array
print("x3 : ", x3)

x1 :  [9 4 0 3 8 6]
x2 :  [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
x3 :  [[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [44]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64


## Array Indexing: Accessing Single Elements

In [45]:
x1

array([9, 4, 0, 3, 8, 6])

In [46]:
print(x1[0])

9


In [47]:
x1[4]

np.int64(8)

In [48]:
x1[-1]

np.int64(6)

In [49]:
x1[-2]

np.int64(8)

In [50]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [51]:
x2[0, 0]

np.int64(3)

In [52]:
x2[2, 0]

np.int64(0)

In [53]:
x2[2, -1]

np.int64(9)

In [54]:
x2[0, 0] = 12 # values can also be modified 
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [55]:
x1[0] = 3.14159 # this will be truncated! 
x1

array([3, 4, 0, 3, 8, 6])

## One-Dimensional Subarrays

In [56]:
x1

array([3, 4, 0, 3, 8, 6])

In [57]:
x1[:3] # first three elements

array([3, 4, 0])

In [58]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [59]:
x1[1: 4] # middle subarray

array([4, 0, 3])

In [60]:
x1 [::2] # every second element

array([3, 0, 8])

In [61]:
x1 [1::2] # every second element, starting at index 1

array([4, 3, 6])

In [62]:
x1[::-1] # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [63]:
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 3])

## Multidimensional Subarrays

In [64]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [65]:
x2 [:2, :3] # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [66]:
x2 [:3, ::2] # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [67]:
x2[::-1, ::-1] #all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [68]:
x2 [:, 0] # first column of x2

array([12,  4,  0])

In [69]:
x2 [0, :] # first row of x2

array([12,  1,  3,  7])

In [72]:
x2[0] # equivalent to x2[0, :]

array([12,  1,  3,  7])

In [73]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [75]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]
