In [1]:
import numpy as np
rng = np.random.default_rng(seed= 1701) # seed for reproducibility

x1= rng.integers(10, size= 6) 
print("x1 : ",x1)
x2= rng.integers(10, size=(3,4)) # two-dimensional array
print("x2 : ",x2)
x3= rng.integers(10, size= (3, 4, 5)) #three-dimensional array
print("x3 : ", x3)

x1 :  [9 4 0 3 8 6]
x2 :  [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
x3 :  [[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64


## Array Indexing: Accessing Single Elements

In [3]:
x1

array([9, 4, 0, 3, 8, 6])

In [4]:
print(x1[0])

9


In [5]:
x1[4]

np.int64(8)

In [6]:
x1[-1]

np.int64(6)

In [7]:
x1[-2]

np.int64(8)

In [8]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [9]:
x2[0, 0]

np.int64(3)

In [10]:
x2[2, 0]

np.int64(0)

In [11]:
x2[2, -1]

np.int64(9)

In [12]:
x2[0, 0] = 12 # values can also be modified 
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [13]:
x1[0] = 3.14159 # this will be truncated! 
x1

array([3, 4, 0, 3, 8, 6])

## One-Dimensional Subarrays

In [14]:
x1

array([3, 4, 0, 3, 8, 6])

In [15]:
x1[:3] # first three elements

array([3, 4, 0])

In [16]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [17]:
x1[1: 4] # middle subarray

array([4, 0, 3])

In [18]:
x1 [::2] # every second element

array([3, 0, 8])

In [19]:
x1 [1::2] # every second element, starting at index 1

array([4, 3, 6])

In [20]:
x1[::-1] # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [21]:
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 3])

## Multidimensional Subarrays

In [22]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [23]:
x2 [:2, :3] # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [24]:
x2 [:3, ::2] # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [25]:
x2[::-1, ::-1] #all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [26]:
x2 [:, 0] # first column of x2

array([12,  4,  0])

In [27]:
x2 [0, :] # first row of x2

array([12,  1,  3,  7])

In [28]:
x2[0] # equivalent to x2[0, :]

array([12,  1,  3,  7])

## Subarrays as No-Copy Views

In [29]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [30]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


In [31]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [32]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [33]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [34]:
# if we modify this subarray, the original array is not touched:
x2_sub_copy[0, 0]= 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [35]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## Reshaping of Arrays

In [36]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
x= np.array([1, 2, 3])
x.reshape((1,3)) # row vector via reshape

array([[1, 2, 3]])

In [38]:
x.reshape((3, 1)) # column vector via reshape

array([[1],
       [2],
       [3]])

In [39]:
x[np.newaxis, : ] # row vector via newaxis


array([[1, 2, 3]])

In [40]:
x[:, np.newaxis] # column vector via newaxis

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

### Concatenation of Arrays

In [52]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [42]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [43]:
# can also be used for 2D arrays:
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])

In [44]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [46]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# horizontal stack the arrays
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### Splitting of Arrays

In [48]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3= np.split(x, [3, 5]) # split the array at index 3 and index 5
print(x1, x2, x3)

# [1 2 3 | 99 99 | 3 2 1]
#        ↑       ↑
#      index3  index5


[1 2 3] [99 99] [3 2 1]


In [49]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [51]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
